version: "3.8"
services:
  postgres:
    build:
      context: ./backend
      dockerfile: ./docker/finnish_postgres.Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: kesaseteli
      POSTGRES_PASSWORD: kesaseteli
      POSTGRES_DB: kesaseteli
      LC_COLLATE: 'fi_FI.UTF-8'
      LC_CTYPE: 'fi_FI.UTF-8'
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: kesaseteli-db

  kesaseteli-backend:
    build:
      context: ./backend
      dockerfile: ./docker/kesaseteli.Dockerfile
      target: development
    env_file:
      - .env.kesaseteli
    environment:
      DATABASE_URL: postgres://kesaseteli:kesaseteli@kesaseteli-db/kesaseteli
      DATABASE_HOST: kesaseteli-db.helsinki
    volumes:
      - ./backend/kesaseteli:/app
      - ./backend/shared:/shared
      - ./backend/kesaseteli/media:/var/media
    depends_on:
      - postgres
    container_name: kesaseteli-backend

  kesaseteli-youth:
    build:
      context: ./frontend
      target: development
      args:
        PORT: 3100
        PROJECT: kesaseteli
        FOLDER: youth
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.kesaseteli
    container_name: kesaseteli-youth

  kesaseteli-handler:
    build:
      context: ./frontend
      target: development
      args:
        PORT: 3200
        PROJECT: kesaseteli
        FOLDER: handler
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.kesaseteli
    container_name: kesaseteli-handler

  kesaseteli-local-proxy:
    depends_on:
      - postgres
      - kesaseteli-backend
      - kesaseteli-handler
      - kesaseteli-youth
    build:
      context: ./localdevelopment/handler/nginx
    container_name: handler-local-proxy
    volumes:
      - ./localdevelopment/handler/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:3100:3100
      - 127.0.0.1:3200:3200

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
