name: (KS Employer) Frontend Lint, Unit and Component tests

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/ks-empl-frontend-tests.yml"
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@main
    secrets: inherit
    with:
      node-version: 22.x
      working-directory: ./frontend/kesaseteli/employer
      extra-commands: echo 'NEXTJS_DISABLE_SENTRY=true' >> .env
