name: Shared Lint, Unit and Component tests

on:
  pull_request:
    paths:
      - ".github/workflows/shared-tests.yml"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@main
    secrets: inherit
    with:
      node-version: 22.x
      working-directory: ./frontend
      app-directory: ./frontend/shared
      skip-build: true