name: Build & Staging
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_required:
        description: "Build images (true/false)"
        required: true
        default: "false"

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: "build_artifacts"
  SERVICE_ARTIFACT_FOLDER: "service_artifacts"
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  K8S_REQUEST_CPU: 2m
  K8S_REQUEST_RAM: 200Mi
  K8S_LIMIT_CPU: 500m
  K8S_LIMIT_RAM: 250Mi
  K8S_REPLICACOUNT: 2
  VAULT_JWT_PRIVATE_KEY: ${{ secrets.VAULT_ACCESS_PRIVATE_KEY_STAGING }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  VAULT_KV_VERSION: "2"

jobs:
  build:
    if: github.event_name == 'push' || github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        dir: ["backend"]
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        if: github.event_name == 'push' || github.event.inputs.build_required == 'true'
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_BUILD_SOURCE: ./${{ matrix.dir }}/Dockerfile
          DOCKER_BUILD_CONTEXT: ./${{ matrix.dir }}
          DOCKER_IMAGE_NAME: ${{ matrix.dir }}

  staging:
    if: github.event_name == 'push' || github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        service: ["backend"]
        include:
        - service: "backend"
          dir: "backend"
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Service with ingress
        run: |
          echo "ENVIRONMENT_URL=https://${{ matrix.service }}.kesaseteli.${{ env.BASE_DOMAIN }}" >> $GITHUB_ENV
          echo "K8S_SECRET_ALLOWED_HOSTS=*" >> $GITHUB_ENV

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: "staging"
        env:
          DOCKER_BUILD_SOURCE: ./${{ matrix.dir }}/Dockerfile
          DOCKER_BUILD_CONTEXT: ./${{ matrix.dir }}
          DOCKER_IMAGE_NAME: ${{ matrix.dir }}
          PROJECT_NAME: ${{ github.event.repository.name }}-${{ matrix.service }}
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          K8S_SECRET_VERSION: ${{ github.sha }}
          VAULT_JWT_AUTH_PATH: ${{ github.event.repository.name }}-${{ matrix.service }}-staging
          VAULT_KV_SECRET_MOUNT_POINT: staging
